apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
      app.kubernetes.io/name: rabbitmq-keda-cluster
      app.kubernetes.io/part-of: rabbitmq
  podMetricsEndpoints:
  - targetPort: 15692
    interval: 10s
